-- ADR-0010 鲜艳色板：旧色名 → 新色名（moss/pine→green、amber→orange、indigo→blue、ochre→red、teal→cyan、plum→purple）
ALTER TABLE "calendars" DROP CONSTRAINT "calendars_color_ck";--> statement-breakpoint
UPDATE "calendars" SET "color" = CASE "color" WHEN 'moss' THEN 'green' WHEN 'pine' THEN 'green' WHEN 'amber' THEN 'orange' WHEN 'indigo' THEN 'blue' WHEN 'ochre' THEN 'red' WHEN 'teal' THEN 'cyan' WHEN 'plum' THEN 'purple' ELSE "color" END;--> statement-breakpoint
UPDATE "spaces" SET "color" = CASE "color" WHEN 'moss' THEN 'green' WHEN 'pine' THEN 'green' WHEN 'amber' THEN 'orange' WHEN 'indigo' THEN 'blue' WHEN 'ochre' THEN 'red' WHEN 'teal' THEN 'cyan' WHEN 'plum' THEN 'purple' ELSE "color" END WHERE "color" IS NOT NULL;--> statement-breakpoint
UPDATE "tags" SET "color" = CASE "color" WHEN 'moss' THEN 'green' WHEN 'pine' THEN 'green' WHEN 'amber' THEN 'orange' WHEN 'indigo' THEN 'blue' WHEN 'ochre' THEN 'red' WHEN 'teal' THEN 'cyan' WHEN 'plum' THEN 'purple' ELSE "color" END;--> statement-breakpoint
ALTER TABLE "calendars" ADD CONSTRAINT "calendars_color_ck" CHECK ("calendars"."color" in ('blue', 'orange', 'yellow', 'red', 'green', 'purple', 'pink', 'cyan', 'gray'));--> statement-breakpoint
-- ADR-0010 用户管理 / 个人资料：审计 action +auth.password_changed / user.created / user.updated
ALTER TABLE "audit_log" DROP CONSTRAINT "audit_log_action_ck";--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_action_ck" CHECK ("audit_log"."action" in ('auth.login', 'auth.logout', 'auth.login_failed', 'auth.locked', 'auth.password_reset', 'auth.password_changed', 'auth.2fa_enabled', 'auth.2fa_disabled', 'auth.2fa_reset_by_admin', 'member.invited', 'member.joined', 'member.registered', 'member.approved', 'member.rejected', 'member.role_changed', 'member.suspended', 'member.unsuspended', 'member.removed', 'member.content_transferred', 'user.created', 'user.updated', 'user.deleted', 'workspace.owner_transferred', 'workspace.settings_changed', 'space.deleted', 'space.permanently_deleted', 'task.permanently_deleted', 'entry.permanently_deleted', 'export.requested', 'export.done', 'export.failed', 'api_key.created', 'api_key.revoked', 'gc.failed', 'backup.failed'));
