/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppDesignRouteImport } from './routes/_app.design'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppTrashRouteImport } from './routes/_app.trash'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as Login2faRouteImport } from './routes/login_.2fa'
import { Route as AppEntriesIndexRouteImport } from './routes/_app.entries.index'
import { Route as AppEntriesEntryIdRouteImport } from './routes/_app.entries.$entryId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app.settings.api-keys'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppSpacesIndexRouteImport } from './routes/_app.spaces.index'
import { Route as AppSpacesSpaceSlugRouteImport } from './routes/_app.spaces.$spaceSlug'
import { Route as AppSettingsWorkspaceIndexRouteImport } from './routes/_app.settings.workspace.index'
import { Route as AppSettingsWorkspaceAuditRouteImport } from './routes/_app.settings.workspace.audit'
import { Route as AppSettingsWorkspaceMembersRouteImport } from './routes/_app.settings.workspace.members'
import { Route as AppSettingsWorkspaceUsersRouteImport } from './routes/_app.settings.workspace.users'
import { Route as AppSpacesSpaceSlugEntriesRouteImport } from './routes/_app.spaces.$spaceSlug_.entries'
import { Route as AppSpacesSpaceSlugTasksTaskIdRouteImport } from './routes/_app.spaces.$spaceSlug.tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignRoute = AppDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const Login2faRoute = Login2faRouteImport.update({
  id: '/login_/2fa',
  path: '/login/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEntriesIndexRoute = AppEntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesEntryIdRoute = AppEntriesEntryIdRouteImport.update({
  id: '/entries/$entryId',
  path: '/entries/$entryId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSpacesIndexRoute = AppSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesSpaceSlugRoute = AppSpacesSpaceSlugRouteImport.update({
  id: '/spaces/$spaceSlug',
  path: '/spaces/$spaceSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsWorkspaceIndexRoute =
  AppSettingsWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsWorkspaceAuditRoute =
  AppSettingsWorkspaceAuditRouteImport.update({
    id: '/workspace/audit',
    path: '/workspace/audit',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsWorkspaceMembersRoute =
  AppSettingsWorkspaceMembersRouteImport.update({
    id: '/workspace/members',
    path: '/workspace/members',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsWorkspaceUsersRoute =
  AppSettingsWorkspaceUsersRouteImport.update({
    id: '/workspace/users',
    path: '/workspace/users',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSpacesSpaceSlugEntriesRoute =
  AppSpacesSpaceSlugEntriesRouteImport.update({
    id: '/spaces/$spaceSlug_/entries',
    path: '/spaces/$spaceSlug/entries',
    getParentRoute: () => AppRoute,
  } as any)
const AppSpacesSpaceSlugTasksTaskIdRoute =
  AppSpacesSpaceSlugTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AppSpacesSpaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/calendar': typeof AppCalendarRoute
  '/design': typeof AppDesignRoute
  '/inbox': typeof AppInboxRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/today': typeof AppTodayRoute
  '/trash': typeof AppTrashRoute
  '/invite/$token': typeof InviteTokenRoute
  '/login/2fa': typeof Login2faRoute
  '/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/spaces/$spaceSlug': typeof AppSpacesSpaceSlugRouteWithChildren
  '/entries/': typeof AppEntriesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/spaces/': typeof AppSpacesIndexRoute
  '/settings/workspace/audit': typeof AppSettingsWorkspaceAuditRoute
  '/settings/workspace/members': typeof AppSettingsWorkspaceMembersRoute
  '/settings/workspace/users': typeof AppSettingsWorkspaceUsersRoute
  '/spaces/$spaceSlug/entries': typeof AppSpacesSpaceSlugEntriesRoute
  '/settings/workspace/': typeof AppSettingsWorkspaceIndexRoute
  '/spaces/$spaceSlug/tasks/$taskId': typeof AppSpacesSpaceSlugTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/calendar': typeof AppCalendarRoute
  '/design': typeof AppDesignRoute
  '/inbox': typeof AppInboxRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/today': typeof AppTodayRoute
  '/trash': typeof AppTrashRoute
  '/invite/$token': typeof InviteTokenRoute
  '/login/2fa': typeof Login2faRoute
  '/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/spaces/$spaceSlug': typeof AppSpacesSpaceSlugRouteWithChildren
  '/entries': typeof AppEntriesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/spaces': typeof AppSpacesIndexRoute
  '/settings/workspace/audit': typeof AppSettingsWorkspaceAuditRoute
  '/settings/workspace/members': typeof AppSettingsWorkspaceMembersRoute
  '/settings/workspace/users': typeof AppSettingsWorkspaceUsersRoute
  '/spaces/$spaceSlug/entries': typeof AppSpacesSpaceSlugEntriesRoute
  '/settings/workspace': typeof AppSettingsWorkspaceIndexRoute
  '/spaces/$spaceSlug/tasks/$taskId': typeof AppSpacesSpaceSlugTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/design': typeof AppDesignRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/today': typeof AppTodayRoute
  '/_app/trash': typeof AppTrashRoute
  '/invite/$token': typeof InviteTokenRoute
  '/login_/2fa': typeof Login2faRoute
  '/_app/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/spaces/$spaceSlug': typeof AppSpacesSpaceSlugRouteWithChildren
  '/_app/entries/': typeof AppEntriesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/spaces/': typeof AppSpacesIndexRoute
  '/_app/settings/workspace/audit': typeof AppSettingsWorkspaceAuditRoute
  '/_app/settings/workspace/members': typeof AppSettingsWorkspaceMembersRoute
  '/_app/settings/workspace/users': typeof AppSettingsWorkspaceUsersRoute
  '/_app/spaces/$spaceSlug_/entries': typeof AppSpacesSpaceSlugEntriesRoute
  '/_app/settings/workspace/': typeof AppSettingsWorkspaceIndexRoute
  '/_app/spaces/$spaceSlug/tasks/$taskId': typeof AppSpacesSpaceSlugTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/calendar'
    | '/design'
    | '/inbox'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/today'
    | '/trash'
    | '/invite/$token'
    | '/login/2fa'
    | '/entries/$entryId'
    | '/settings/api-keys'
    | '/settings/notifications'
    | '/settings/security'
    | '/spaces/$spaceSlug'
    | '/entries/'
    | '/settings/'
    | '/spaces/'
    | '/settings/workspace/audit'
    | '/settings/workspace/members'
    | '/settings/workspace/users'
    | '/spaces/$spaceSlug/entries'
    | '/settings/workspace/'
    | '/spaces/$spaceSlug/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/calendar'
    | '/design'
    | '/inbox'
    | '/notifications'
    | '/search'
    | '/today'
    | '/trash'
    | '/invite/$token'
    | '/login/2fa'
    | '/entries/$entryId'
    | '/settings/api-keys'
    | '/settings/notifications'
    | '/settings/security'
    | '/spaces/$spaceSlug'
    | '/entries'
    | '/settings'
    | '/spaces'
    | '/settings/workspace/audit'
    | '/settings/workspace/members'
    | '/settings/workspace/users'
    | '/spaces/$spaceSlug/entries'
    | '/settings/workspace'
    | '/spaces/$spaceSlug/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/calendar'
    | '/_app/design'
    | '/_app/inbox'
    | '/_app/notifications'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/today'
    | '/_app/trash'
    | '/invite/$token'
    | '/login_/2fa'
    | '/_app/entries/$entryId'
    | '/_app/settings/api-keys'
    | '/_app/settings/notifications'
    | '/_app/settings/security'
    | '/_app/spaces/$spaceSlug'
    | '/_app/entries/'
    | '/_app/settings/'
    | '/_app/spaces/'
    | '/_app/settings/workspace/audit'
    | '/_app/settings/workspace/members'
    | '/_app/settings/workspace/users'
    | '/_app/spaces/$spaceSlug_/entries'
    | '/_app/settings/workspace/'
    | '/_app/spaces/$spaceSlug/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  Login2faRoute: typeof Login2faRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design': {
      id: '/_app/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AppDesignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/2fa': {
      id: '/login_/2fa'
      path: '/login/2fa'
      fullPath: '/login/2fa'
      preLoaderRoute: typeof Login2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/entries/': {
      id: '/_app/entries/'
      path: '/entries'
      fullPath: '/entries/'
      preLoaderRoute: typeof AppEntriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/$entryId': {
      id: '/_app/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof AppEntriesEntryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/spaces/': {
      id: '/_app/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AppSpacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spaces/$spaceSlug': {
      id: '/_app/spaces/$spaceSlug'
      path: '/spaces/$spaceSlug'
      fullPath: '/spaces/$spaceSlug'
      preLoaderRoute: typeof AppSpacesSpaceSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/workspace/': {
      id: '/_app/settings/workspace/'
      path: '/workspace'
      fullPath: '/settings/workspace/'
      preLoaderRoute: typeof AppSettingsWorkspaceIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/workspace/audit': {
      id: '/_app/settings/workspace/audit'
      path: '/workspace/audit'
      fullPath: '/settings/workspace/audit'
      preLoaderRoute: typeof AppSettingsWorkspaceAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/workspace/members': {
      id: '/_app/settings/workspace/members'
      path: '/workspace/members'
      fullPath: '/settings/workspace/members'
      preLoaderRoute: typeof AppSettingsWorkspaceMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/workspace/users': {
      id: '/_app/settings/workspace/users'
      path: '/workspace/users'
      fullPath: '/settings/workspace/users'
      preLoaderRoute: typeof AppSettingsWorkspaceUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/spaces/$spaceSlug_/entries': {
      id: '/_app/spaces/$spaceSlug_/entries'
      path: '/spaces/$spaceSlug/entries'
      fullPath: '/spaces/$spaceSlug/entries'
      preLoaderRoute: typeof AppSpacesSpaceSlugEntriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spaces/$spaceSlug/tasks/$taskId': {
      id: '/_app/spaces/$spaceSlug/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/spaces/$spaceSlug/tasks/$taskId'
      preLoaderRoute: typeof AppSpacesSpaceSlugTasksTaskIdRouteImport
      parentRoute: typeof AppSpacesSpaceSlugRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsWorkspaceAuditRoute: typeof AppSettingsWorkspaceAuditRoute
  AppSettingsWorkspaceMembersRoute: typeof AppSettingsWorkspaceMembersRoute
  AppSettingsWorkspaceUsersRoute: typeof AppSettingsWorkspaceUsersRoute
  AppSettingsWorkspaceIndexRoute: typeof AppSettingsWorkspaceIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsWorkspaceAuditRoute: AppSettingsWorkspaceAuditRoute,
  AppSettingsWorkspaceMembersRoute: AppSettingsWorkspaceMembersRoute,
  AppSettingsWorkspaceUsersRoute: AppSettingsWorkspaceUsersRoute,
  AppSettingsWorkspaceIndexRoute: AppSettingsWorkspaceIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppSpacesSpaceSlugRouteChildren {
  AppSpacesSpaceSlugTasksTaskIdRoute: typeof AppSpacesSpaceSlugTasksTaskIdRoute
}

const AppSpacesSpaceSlugRouteChildren: AppSpacesSpaceSlugRouteChildren = {
  AppSpacesSpaceSlugTasksTaskIdRoute: AppSpacesSpaceSlugTasksTaskIdRoute,
}

const AppSpacesSpaceSlugRouteWithChildren =
  AppSpacesSpaceSlugRoute._addFileChildren(AppSpacesSpaceSlugRouteChildren)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppDesignRoute: typeof AppDesignRoute
  AppInboxRoute: typeof AppInboxRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTodayRoute: typeof AppTodayRoute
  AppTrashRoute: typeof AppTrashRoute
  AppEntriesEntryIdRoute: typeof AppEntriesEntryIdRoute
  AppSpacesSpaceSlugRoute: typeof AppSpacesSpaceSlugRouteWithChildren
  AppEntriesIndexRoute: typeof AppEntriesIndexRoute
  AppSpacesIndexRoute: typeof AppSpacesIndexRoute
  AppSpacesSpaceSlugEntriesRoute: typeof AppSpacesSpaceSlugEntriesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppDesignRoute: AppDesignRoute,
  AppInboxRoute: AppInboxRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTodayRoute: AppTodayRoute,
  AppTrashRoute: AppTrashRoute,
  AppEntriesEntryIdRoute: AppEntriesEntryIdRoute,
  AppSpacesSpaceSlugRoute: AppSpacesSpaceSlugRouteWithChildren,
  AppEntriesIndexRoute: AppEntriesIndexRoute,
  AppSpacesIndexRoute: AppSpacesIndexRoute,
  AppSpacesSpaceSlugEntriesRoute: AppSpacesSpaceSlugEntriesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  Login2faRoute: Login2faRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
